version: "3.4"
services:
  app:
    build:
      context: .
      target: develop
    environment:
      - GO_ENV=develop
    volumes:
      - ./:/go/src
      - gomod-data:/go/pkg/mod/
    ports:
      - "8087:8080"
    tty: true

volumes:
  gomod-data:
