version: "3.4"
services:
  app:
    build:
      context: .
      target: release
    environment:
      - GO_ENV=production
    volumes:
      - ./:/go/src
    ports:
      - "8087:8080"
